language: ruby
rvm:
 - 2.3.1

sudo: required
dist: trusty

before script:
  - if: branch = master
      docker login -p="$DOCKER_PASSWORD"-p="(\['>$DOCKER_USERNAME";
      docker build -f Dockerfile -t $REPO . ;
      docker push jamesabrown/gatekeeper;
      fi
  - echo "$DOCKER_PASSWORD"
  - echo "$SECRET ^ A"

script:
 - bundle exec rake test
